### PR TITLE
Fix documentation to match correct usage

### PR DESCRIPTION
**Pull request by TigerWolf**
A change 10 months ago removed how you could access the custom prompts, this commit updates the documentation to ensure it matches.

### CODE REVIEW

**Comment by banister** [comment]
ping @kyrylo  😅

**Comment by TigerWolf** [comment]
For context: https://github.com/rweng/pry-rails/commit/a20b2976755e271f3ac10ff3bc52d924c69d992e#diff-6c60141c6c6a94f3141814deccf2645c

**Comment by TigerWolf** [comment]
Its worth noting that this comment is relevant but does not work: https://github.com/rweng/pry-rails/pull/105#issuecomment-442976993

**Comment by TigerWolf** [comment]
I have updated the code as this changes when upgrading from pry v11 to v12.

**Comment by TigerWolf** [comment]
Not needed, this can be solved by upgrading pry to v12.

**Pull request closed without merging**
